apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  labels:
    app: database
spec:
  type: NodePort
  selector:
    app: database
  ports:
    - port: 3306
      targetPort: 3306
      nodePort: 31000
