apiVersion: v1
kind: Service
metadata:
  name: sprint-boot-service
  labels:
    app: backend
spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - port: 5001
      targetPort: 5001
      nodePort: 32000
